In [1]:
import pandas as pd

In [2]:
#Let's read in the data as we've taken it from the CDC 


city_level_data = pd.read_csv(
    "500_Cities__Local_Data_for_Better_Health,_2019_release_20260524.csv",
    engine="python",
    quoting=3,
    on_bad_lines="skip",
    encoding_errors="ignore"
)

In [3]:
# Quick Inspection to see how everything looks

city_level_data.head()

                   "Year"  "StateAbbr"     "StateDesc" "CityName"  \
"2017" "CA"  "California"  "Hawthorne"  "Census Tract"    "BRFSS"
       "CA"  "California"  "Hawthorne"          "City"    "BRFSS"
       "CA"  "California"    "Hayward"          "City"    "BRFSS"
       "CA"  "California"    "Hayward"          "City"    "BRFSS"
       "CA"  "California"      "Hemet"          "City"    "BRFSS"

                 "GeographicLevel"           "DataSource"  \
"2017" "CA"      "Health Outcomes"  "0632548-06037602504"
       "CA"  "Unhealthy Behaviors"              "0632548"
       "CA"      "Health Outcomes"              "0633000"
       "CA"  "Unhealthy Behaviors"              "0633000"
       "CA"           "Prevention"              "0633182"

                                                    "Category" "UniqueID"  \
"2017" "CA"           "Arthritis among adults aged >=18 Years"        "%"
       "CA"     "Current smoking among adults aged >=18 Years"        "%"
       "CA"  "Coronary heart disease among adults aged >=18...        "%"
       "CA"             "Obesity among adults aged >=18 Years"        "%"
       "CA"  "Cholesterol screening among adults aged >=18 ...        "%"

               "Measure"          "Data_Value_Unit"  ...  \
"2017" "CA"     "CrdPrv"         "Crude prevalence"  ...
       "CA"     "CrdPrv"         "Crude prevalence"  ...
       "CA"  "AgeAdjPrv"  "Age-adjusted prevalence"  ...
       "CA"     "CrdPrv"         "Crude prevalence"  ...
       "CA"  "AgeAdjPrv"  "Age-adjusted prevalence"  ...

            "High_Confidence_Limit" "Data_Value_Footnote_Symbol"  \
"2017" "CA"                     NaN                           "4
       "CA"                     NaN                          "84
       "CA"                     NaN                         "144
       "CA"                     NaN                         "144
       "CA"                     NaN                          "78

            "Data_Value_Footnote"    "PopulationCount"      "GeoLocation"  \
"2017" "CA"                  407"   "    (33.905547923   -118.337332298)"
       "CA"                  293"   "    (33.914667701   -118.347667728)"
       "CA"                  186"  "    (37.6329591551   -122.077051051)"
       "CA"                  186"  "    (37.6329591551   -122.077051051)"
       "CA"                  657"  "    (33.7352277311   -116.994605005)"

            "CategoryID"   "MeasureId" "CityFIPS"    "TractFIPS"  \
"2017" "CA"    "HLTHOUT"   "ARTHRITIS"  "0632548"  "06037602504"
       "CA"     "UNHBEH"    "CSMOKING"  "0632548"            NaN
       "CA"    "HLTHOUT"         "CHD"  "0633000"            NaN
       "CA"     "UNHBEH"     "OBESITY"  "0633000"            NaN
       "CA"    "PREVENT"  "CHOLSCREEN"  "0633182"            NaN

                "Short_Question_Text"
"2017" "CA"               "Arthritis"
       "CA"         "Current Smoking"
       "CA"  "Coronary Heart Disease"
       "CA"                 "Obesity"
       "CA"   "Cholesterol Screening"

[5 rows x 24 columns]

In [4]:
# The data imported a little strange, so we're going to shift to make the Header appear in the first column instead of the third like it does.  

city_level_data = pd.read_csv(
    "500_Cities__Local_Data_for_Better_Health,_2019_release_20260524.csv",
    sep=",",
    header=0
)

In [5]:
#Quick Check to see what all our individual column names are and to see if our reread in worked. 

print(city_level_data.columns)
city_level_data.head()

Index(['Year', 'StateAbbr', 'StateDesc', 'CityName', 'GeographicLevel',
       'DataSource', 'Category', 'UniqueID', 'Measure', 'Data_Value_Unit',
       'DataValueTypeID', 'Data_Value_Type', 'Data_Value',
       'Low_Confidence_Limit', 'High_Confidence_Limit',
       'Data_Value_Footnote_Symbol', 'Data_Value_Footnote', 'PopulationCount',
       'GeoLocation', 'CategoryID', 'MeasureId', 'CityFIPS', 'TractFIPS',
       'Short_Question_Text'],
      dtype='str')

,Year,StateAbbr,StateDesc,CityName,GeographicLevel,DataSource,Category,UniqueID,Measure,Data_Value_Unit,...,High_Confidence_Limit,Data_Value_Footnote_Symbol,Data_Value_Footnote,PopulationCount,GeoLocation,CategoryID,MeasureId,CityFIPS,TractFIPS,Short_Question_Text
0,2017,CA,California,Hawthorne,Census Tract,BRFSS,Health Outcomes,0632548-06037602504,Arthritis among adults aged >=18 Years,%,...,15.2,NaN,NaN,"4,407","(33.905547923, -118.337332298)",HLTHOUT,ARTHRITIS,632548.0,6.037603e+09,Arthritis
1,2017,CA,California,Hawthorne,City,BRFSS,Unhealthy Behaviors,0632548,Current smoking among adults aged >=18 Years,%,...,15.9,NaN,NaN,"84,293","(33.914667701, -118.347667728)",UNHBEH,CSMOKING,632548.0,NaN,Current Smoking
2,2017,CA,California,Hayward,City,BRFSS,Health Outcomes,0633000,Coronary heart disease among adults aged >=18 ...,%,...,4.8,NaN,NaN,"144,186","(37.6329591551, -122.077051051)",HLTHOUT,CHD,633000.0,NaN,Coronary Heart Disease
3,2017,CA,California,Hayward,City,BRFSS,Unhealthy Behaviors,0633000,Obesity among adults aged >=18 Years,%,...,24.4,NaN,NaN,"144,186","(37.6329591551, -122.077051051)",UNHBEH,OBESITY,633000.0,NaN,Obesity
4,2017,CA,California,Hemet,City,BRFSS,Prevention,0633182,Cholesterol screening among adults aged >=18 Y...,%,...,78.3,NaN,NaN,"78,657","(33.7352277311, -116.994605005)",PREVENT,CHOLSCREEN,633182.0,NaN,Cholesterol Screening

In [6]:
# I really only want to focus on data at the city level such that I can map it to counties in the United States, so let's just strip that column to only represent city data. 

city_level_data = city_level_data[
    city_level_data["GeographicLevel"].str.strip().str.lower() == "city"
]

In [7]:
# Let's check to see if that's the only data left and how many rows that leaves us.

city_level_data["GeographicLevel"].value_counts()

GeographicLevel
City    28000
Name: count, dtype: int64

In [8]:
city_level_data.head()

,Year,StateAbbr,StateDesc,CityName,GeographicLevel,DataSource,Category,UniqueID,Measure,Data_Value_Unit,...,High_Confidence_Limit,Data_Value_Footnote_Symbol,Data_Value_Footnote,PopulationCount,GeoLocation,CategoryID,MeasureId,CityFIPS,TractFIPS,Short_Question_Text
1,2017,CA,California,Hawthorne,City,BRFSS,Unhealthy Behaviors,0632548,Current smoking among adults aged >=18 Years,%,...,15.9,NaN,NaN,"84,293","(33.914667701, -118.347667728)",UNHBEH,CSMOKING,632548.0,NaN,Current Smoking
2,2017,CA,California,Hayward,City,BRFSS,Health Outcomes,0633000,Coronary heart disease among adults aged >=18 ...,%,...,4.8,NaN,NaN,"144,186","(37.6329591551, -122.077051051)",HLTHOUT,CHD,633000.0,NaN,Coronary Heart Disease
3,2017,CA,California,Hayward,City,BRFSS,Unhealthy Behaviors,0633000,Obesity among adults aged >=18 Years,%,...,24.4,NaN,NaN,"144,186","(37.6329591551, -122.077051051)",UNHBEH,OBESITY,633000.0,NaN,Obesity
4,2017,CA,California,Hemet,City,BRFSS,Prevention,0633182,Cholesterol screening among adults aged >=18 Y...,%,...,78.3,NaN,NaN,"78,657","(33.7352277311, -116.994605005)",PREVENT,CHOLSCREEN,633182.0,NaN,Cholesterol Screening
6,2017,CA,California,Indio,City,BRFSS,Unhealthy Behaviors,0636448,Binge drinking among adults aged >=18 Years,%,...,17.9,NaN,NaN,"76,036","(33.7298067837, -116.237258141)",UNHBEH,BINGE,636448.0,NaN,Binge Drinking

In [9]:
# We're going to explore some columns to see if they're really necessary of if they even have any differences. 

for val in city_level_data["DataSource"].unique():
    print(repr(val))

'BRFSS'

In [10]:
# Let's start dropping unnecessary stuff

city_level_data = city_level_data.drop(columns=["DataSource"])

In [11]:
"DataSource" in city_level_data.columns

False

In [12]:
for val in city_level_data["Data_Value_Unit"].unique():
    print(repr(val))

'%'

In [13]:
city_level_data = city_level_data.drop(columns=["Data_Value_Unit"])

In [14]:
"Data_Value_Unit" in city_level_data.columns

False

In [15]:
city_level_data = city_level_data.drop(columns=["DataValueTypeID"])

In [16]:
"DataValueTypeID" in city_level_data.columns

False

In [17]:
# now an idea of what we have left

city_level_data.head()

,Year,StateAbbr,StateDesc,CityName,GeographicLevel,Category,UniqueID,Measure,Data_Value_Type,Data_Value,...,High_Confidence_Limit,Data_Value_Footnote_Symbol,Data_Value_Footnote,PopulationCount,GeoLocation,CategoryID,MeasureId,CityFIPS,TractFIPS,Short_Question_Text
1,2017,CA,California,Hawthorne,City,Unhealthy Behaviors,0632548,Current smoking among adults aged >=18 Years,Crude prevalence,15.4,...,15.9,NaN,NaN,"84,293","(33.914667701, -118.347667728)",UNHBEH,CSMOKING,632548.0,NaN,Current Smoking
2,2017,CA,California,Hayward,City,Health Outcomes,0633000,Coronary heart disease among adults aged >=18 ...,Age-adjusted prevalence,4.8,...,4.8,NaN,NaN,"144,186","(37.6329591551, -122.077051051)",HLTHOUT,CHD,633000.0,NaN,Coronary Heart Disease
3,2017,CA,California,Hayward,City,Unhealthy Behaviors,0633000,Obesity among adults aged >=18 Years,Crude prevalence,24.2,...,24.4,NaN,NaN,"144,186","(37.6329591551, -122.077051051)",UNHBEH,OBESITY,633000.0,NaN,Obesity
4,2017,CA,California,Hemet,City,Prevention,0633182,Cholesterol screening among adults aged >=18 Y...,Age-adjusted prevalence,78.0,...,78.3,NaN,NaN,"78,657","(33.7352277311, -116.994605005)",PREVENT,CHOLSCREEN,633182.0,NaN,Cholesterol Screening
6,2017,CA,California,Indio,City,Unhealthy Behaviors,0636448,Binge drinking among adults aged >=18 Years,Age-adjusted prevalence,17.7,...,17.9,NaN,NaN,"76,036","(33.7298067837, -116.237258141)",UNHBEH,BINGE,636448.0,NaN,Binge Drinking

In [18]:
# still lots to drop

city_level_data = city_level_data.drop(columns=["Data_Value_Footnote_Symbol", "Data_Value_Footnote"])

In [19]:
city_level_data.head()

,Year,StateAbbr,StateDesc,CityName,GeographicLevel,Category,UniqueID,Measure,Data_Value_Type,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,PopulationCount,GeoLocation,CategoryID,MeasureId,CityFIPS,TractFIPS,Short_Question_Text
1,2017,CA,California,Hawthorne,City,Unhealthy Behaviors,0632548,Current smoking among adults aged >=18 Years,Crude prevalence,15.4,15.0,15.9,"84,293","(33.914667701, -118.347667728)",UNHBEH,CSMOKING,632548.0,NaN,Current Smoking
2,2017,CA,California,Hayward,City,Health Outcomes,0633000,Coronary heart disease among adults aged >=18 ...,Age-adjusted prevalence,4.8,4.7,4.8,"144,186","(37.6329591551, -122.077051051)",HLTHOUT,CHD,633000.0,NaN,Coronary Heart Disease
3,2017,CA,California,Hayward,City,Unhealthy Behaviors,0633000,Obesity among adults aged >=18 Years,Crude prevalence,24.2,24.1,24.4,"144,186","(37.6329591551, -122.077051051)",UNHBEH,OBESITY,633000.0,NaN,Obesity
4,2017,CA,California,Hemet,City,Prevention,0633182,Cholesterol screening among adults aged >=18 Y...,Age-adjusted prevalence,78.0,77.6,78.3,"78,657","(33.7352277311, -116.994605005)",PREVENT,CHOLSCREEN,633182.0,NaN,Cholesterol Screening
6,2017,CA,California,Indio,City,Unhealthy Behaviors,0636448,Binge drinking among adults aged >=18 Years,Age-adjusted prevalence,17.7,17.5,17.9,"76,036","(33.7298067837, -116.237258141)",UNHBEH,BINGE,636448.0,NaN,Binge Drinking

In [20]:
city_level_data = city_level_data.drop(columns=["CityFIPS", "TractFIPS", "MeasureId", "CategoryID"])

In [21]:
city_level_data.head()

,Year,StateAbbr,StateDesc,CityName,GeographicLevel,Category,UniqueID,Measure,Data_Value_Type,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,PopulationCount,GeoLocation,Short_Question_Text
1,2017,CA,California,Hawthorne,City,Unhealthy Behaviors,0632548,Current smoking among adults aged >=18 Years,Crude prevalence,15.4,15.0,15.9,"84,293","(33.914667701, -118.347667728)",Current Smoking
2,2017,CA,California,Hayward,City,Health Outcomes,0633000,Coronary heart disease among adults aged >=18 ...,Age-adjusted prevalence,4.8,4.7,4.8,"144,186","(37.6329591551, -122.077051051)",Coronary Heart Disease
3,2017,CA,California,Hayward,City,Unhealthy Behaviors,0633000,Obesity among adults aged >=18 Years,Crude prevalence,24.2,24.1,24.4,"144,186","(37.6329591551, -122.077051051)",Obesity
4,2017,CA,California,Hemet,City,Prevention,0633182,Cholesterol screening among adults aged >=18 Y...,Age-adjusted prevalence,78.0,77.6,78.3,"78,657","(33.7352277311, -116.994605005)",Cholesterol Screening
6,2017,CA,California,Indio,City,Unhealthy Behaviors,0636448,Binge drinking among adults aged >=18 Years,Age-adjusted prevalence,17.7,17.5,17.9,"76,036","(33.7298067837, -116.237258141)",Binge Drinking

In [22]:
city_level_data.columns

Index(['Year', 'StateAbbr', 'StateDesc', 'CityName', 'GeographicLevel',
       'Category', 'UniqueID', 'Measure', 'Data_Value_Type', 'Data_Value',
       'Low_Confidence_Limit', 'High_Confidence_Limit', 'PopulationCount',
       'GeoLocation', 'Short_Question_Text'],
      dtype='str')

In [23]:
for columns in city_level_data.columns: 
    print(columns)

Year
StateAbbr
StateDesc
CityName
GeographicLevel
Category
UniqueID
Measure
Data_Value_Type
Data_Value
Low_Confidence_Limit
High_Confidence_Limit
PopulationCount
GeoLocation
Short_Question_Text

In [24]:
city_level_data = city_level_data.drop(columns=["Short_Question_Text", "GeoLocation"])
city_level_data.columns

Index(['Year', 'StateAbbr', 'StateDesc', 'CityName', 'GeographicLevel',
       'Category', 'UniqueID', 'Measure', 'Data_Value_Type', 'Data_Value',
       'Low_Confidence_Limit', 'High_Confidence_Limit', 'PopulationCount'],
      dtype='str')

In [25]:
for columns in city_level_data.columns: 
    print(columns)

Year
StateAbbr
StateDesc
CityName
GeographicLevel
Category
UniqueID
Measure
Data_Value_Type
Data_Value
Low_Confidence_Limit
High_Confidence_Limit
PopulationCount

In [26]:
# Let's get a better idea of what's in the remaining columns and whether or not it's useful

city_level_data["Data_Value_Type"]

1                Crude prevalence
2         Age-adjusted prevalence
3                Crude prevalence
4         Age-adjusted prevalence
6         Age-adjusted prevalence
                   ...
809936    Age-adjusted prevalence
809962    Age-adjusted prevalence
809975    Age-adjusted prevalence
810089           Crude prevalence
810097    Age-adjusted prevalence
Name: Data_Value_Type, Length: 28000, dtype: str

In [27]:
city_level_data["Data_Value_Type"].unique()

<ArrowStringArray>
['Crude prevalence', 'Age-adjusted prevalence']
Length: 2, dtype: str

In [28]:
# I'd like to just do age-adjusted prevalence since some counties would skew in health outcomes if they have an overall older population

city_level_data = city_level_data[
    city_level_data["Data_Value_Type"] != "Crude prevalence"
]

In [29]:
city_level_data.head(20)

,Year,StateAbbr,StateDesc,CityName,GeographicLevel,Category,UniqueID,Measure,Data_Value_Type,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,PopulationCount
2,2017,CA,California,Hayward,City,Health Outcomes,0633000,Coronary heart disease among adults aged >=18 ...,Age-adjusted prevalence,4.8,4.7,4.8,"144,186"
4,2017,CA,California,Hemet,City,Prevention,0633182,Cholesterol screening among adults aged >=18 Y...,Age-adjusted prevalence,78.0,77.6,78.3,"78,657"
6,2017,CA,California,Indio,City,Unhealthy Behaviors,0636448,Binge drinking among adults aged >=18 Years,Age-adjusted prevalence,17.7,17.5,17.9,"76,036"
7,2017,CA,California,Indio,City,Health Outcomes,0636448,Chronic obstructive pulmonary disease among ad...,Age-adjusted prevalence,6.0,5.8,6.2,"76,036"
21,2017,AL,Alabama,Mobile,City,Unhealthy Behaviors,0150000,Obesity among adults aged >=18 Years,Age-adjusted prevalence,38.2,38.0,38.3,"195,111"
24,2017,AL,Alabama,Tuscaloosa,City,Health Outcomes,0177256,Stroke among adults aged >=18 Years,Age-adjusted prevalence,4.2,4.1,4.3,"90,468"
36,2017,AZ,Arizona,Scottsdale,City,Prevention,0465000,Cholesterol screening among adults aged >=18 Y...,Age-adjusted prevalence,82.7,82.5,82.9,"217,385"
42,2016,AR,Arkansas,Jonesboro,City,Health Outcomes,0535710,All teeth lost among adults aged >=65 Years,Age-adjusted prevalence,18.0,16.1,20.2,"67,263"
49,2016,CA,California,Antioch,City,Health Outcomes,0602252,All teeth lost among adults aged >=65 Years,Age-adjusted prevalence,13.0,12.1,13.9,"102,372"
50,2017,CA,California,Bellflower,City,Health Outcomes,0604982,Coronary heart disease among adults aged >=18 ...,Age-adjusted prevalence,5.3,5.2,5.4,"76,616"
56,2016,CA,California,Carlsbad,City,Prevention,0611194,Mammography use among women aged 50–74 Years,Age-adjusted prevalence,79.7,79.0,80.4,"105,328"
59,2016,CA,California,Chino Hills,City,Health Outcomes,0613214,All teeth lost among adults aged >=65 Years,Age-adjusted prevalence,8.1,7.1,9.1,"74,799"
68,2017,CA,California,Corona,City,Unhealthy Behaviors,0616350,Obesity among adults aged >=18 Years,Age-adjusted prevalence,26.8,26.6,27.0,"152,374"
76,2016,CA,California,Fairfield,City,Prevention,0623182,Papanicolaou smear use among adult women aged ...,Age-adjusted prevalence,79.0,78.6,79.4,"105,321"
83,2017,CA,California,Fullerton,City,Unhealthy Behaviors,0628000,Binge drinking among adults aged >=18 Years,Age-adjusted prevalence,18.4,18.3,18.5,"135,161"
84,2017,CA,California,Fullerton,City,Unhealthy Behaviors,0628000,Obesity among adults aged >=18 Years,Age-adjusted prevalence,20.5,20.3,20.7,"135,161"
89,2017,CA,California,Lynwood,City,Health Outcomes,0644574,Cancer (excluding skin cancer) among adults ag...,Age-adjusted prevalence,5.0,5.0,5.1,"69,772"
92,2017,CA,California,Menifee,City,Health Outcomes,0646842,Chronic kidney disease among adults aged >=18 ...,Age-adjusted prevalence,2.9,2.9,3.0,"77,519"
97,2017,CA,California,Modesto,City,Prevention,0648354,Cholesterol screening among adults aged >=18 Y...,Age-adjusted prevalence,78.7,78.5,79.0,"201,165"
104,2016,CA,California,Ontario,City,Prevention,0653896,Mammography use among women aged 50–74 Years,Age-adjusted prevalence,77.0,76.5,77.5,"163,924"

In [30]:
# Just a few more columns to drop and then I think we're ready for the next step

city_level_data = city_level_data.drop(columns=["Low_Confidence_Limit", "High_Confidence_Limit", "UniqueID"])
city_level_data.columns

Index(['Year', 'StateAbbr', 'StateDesc', 'CityName', 'GeographicLevel',
       'Category', 'Measure', 'Data_Value_Type', 'Data_Value',
       'PopulationCount'],
      dtype='str')

In [31]:
city_level_data.head()

,Year,StateAbbr,StateDesc,CityName,GeographicLevel,Category,Measure,Data_Value_Type,Data_Value,PopulationCount
2,2017,CA,California,Hayward,City,Health Outcomes,Coronary heart disease among adults aged >=18 ...,Age-adjusted prevalence,4.8,"144,186"
4,2017,CA,California,Hemet,City,Prevention,Cholesterol screening among adults aged >=18 Y...,Age-adjusted prevalence,78.0,"78,657"
6,2017,CA,California,Indio,City,Unhealthy Behaviors,Binge drinking among adults aged >=18 Years,Age-adjusted prevalence,17.7,"76,036"
7,2017,CA,California,Indio,City,Health Outcomes,Chronic obstructive pulmonary disease among ad...,Age-adjusted prevalence,6.0,"76,036"
21,2017,AL,Alabama,Mobile,City,Unhealthy Behaviors,Obesity among adults aged >=18 Years,Age-adjusted prevalence,38.2,"195,111"

In [32]:
# Let's read in the city dataset with county information

us_cities = pd.read_csv("uscities.csv")

In [33]:
# Quick inspection to see if everything imported correctly

us_cities.head()

,city,city_ascii,state_id,state_name,county_fips,county_name,lat,lng,population,density,source,military,incorporated,timezone,ranking,zips,id
0,New York,New York,NY,New York,36081,Queens,40.6943,-73.9249,19268388,10943.7,shape,False,True,America/New_York,1,11229 11228 11226 11225 11224 11222 11221 1122...,1840034016
1,Los Angeles,Los Angeles,CA,California,6037,Los Angeles,34.1141,-118.4068,11984083,3165.7,shape,False,True,America/Los_Angeles,1,91367 90291 90293 90292 91316 91311 90035 9003...,1840020491
2,Chicago,Chicago,IL,Illinois,17031,Cook,41.8375,-87.6866,8609571,4590.3,shape,False,True,America/Chicago,1,60018 60649 60641 60640 60643 60642 60645 6064...,1840000494
3,Miami,Miami,FL,Florida,12086,Miami-Dade,25.7840,-80.2101,6391670,4791.1,shape,False,True,America/New_York,1,33128 33129 33125 33126 33127 33149 33144 3314...,1840015149
4,Houston,Houston,TX,Texas,48201,Harris,29.7860,-95.3885,6227666,1386.2,shape,False,True,America/Chicago,1,77069 77068 77061 77060 77063 77062 77065 7706...,1840020925

In [34]:
# We know only really want to keep the city, state and county columns and everything else can go

us_cities = us_cities.drop(columns=["city_ascii", "county_fips", "lng", "population", "density", "source", "military", "incorporated", "timezone", "ranking", "zips", "id", "lat"])
us_cities.columns

Index(['city', 'state_id', 'state_name', 'county_name'], dtype='str')

In [35]:
# Now we can do a left join on city and state ID for the two datasets 


city_level_data = city_level_data.merge(
    us_cities, 
    left_on=["CityName", "StateAbbr"], 
    right_on=["city", "state_id"], 
    how="left"
              )

In [36]:
city_level_data.head()

,Year,StateAbbr,StateDesc,CityName,GeographicLevel,Category,Measure,Data_Value_Type,Data_Value,PopulationCount,city,state_id,state_name,county_name
0,2017,CA,California,Hayward,City,Health Outcomes,Coronary heart disease among adults aged >=18 ...,Age-adjusted prevalence,4.8,"144,186",Hayward,CA,California,Alameda
1,2017,CA,California,Hemet,City,Prevention,Cholesterol screening among adults aged >=18 Y...,Age-adjusted prevalence,78.0,"78,657",Hemet,CA,California,Riverside
2,2017,CA,California,Indio,City,Unhealthy Behaviors,Binge drinking among adults aged >=18 Years,Age-adjusted prevalence,17.7,"76,036",Indio,CA,California,Riverside
3,2017,CA,California,Indio,City,Health Outcomes,Chronic obstructive pulmonary disease among ad...,Age-adjusted prevalence,6.0,"76,036",Indio,CA,California,Riverside
4,2017,AL,Alabama,Mobile,City,Unhealthy Behaviors,Obesity among adults aged >=18 Years,Age-adjusted prevalence,38.2,"195,111",Mobile,AL,Alabama,Mobile

In [37]:
# To make the columns more clear, let's change names 

city_level_data = city_level_data.rename(columns={
    "county_name": "County", 
    "StateAbbr": "State ID",
    "StateDesc": "State",
    "CityName": "City"
})

In [38]:
city_level_data.columns

Index(['Year', 'State ID', 'State', 'City', 'GeographicLevel', 'Category',
       'Measure', 'Data_Value_Type', 'Data_Value', 'PopulationCount', 'city',
       'state_id', 'state_name', 'County'],
      dtype='str')

In [39]:
city_level_data.head()

,Year,State ID,State,City,GeographicLevel,Category,Measure,Data_Value_Type,Data_Value,PopulationCount,city,state_id,state_name,County
0,2017,CA,California,Hayward,City,Health Outcomes,Coronary heart disease among adults aged >=18 ...,Age-adjusted prevalence,4.8,"144,186",Hayward,CA,California,Alameda
1,2017,CA,California,Hemet,City,Prevention,Cholesterol screening among adults aged >=18 Y...,Age-adjusted prevalence,78.0,"78,657",Hemet,CA,California,Riverside
2,2017,CA,California,Indio,City,Unhealthy Behaviors,Binge drinking among adults aged >=18 Years,Age-adjusted prevalence,17.7,"76,036",Indio,CA,California,Riverside
3,2017,CA,California,Indio,City,Health Outcomes,Chronic obstructive pulmonary disease among ad...,Age-adjusted prevalence,6.0,"76,036",Indio,CA,California,Riverside
4,2017,AL,Alabama,Mobile,City,Unhealthy Behaviors,Obesity among adults aged >=18 Years,Age-adjusted prevalence,38.2,"195,111",Mobile,AL,Alabama,Mobile

In [40]:
# Let's drop the columns that have now been duplicated 

city_level_data = city_level_data.drop(columns=["state_id", "city", "state_name"])
city_level_data.columns

Index(['Year', 'State ID', 'State', 'City', 'GeographicLevel', 'Category',
       'Measure', 'Data_Value_Type', 'Data_Value', 'PopulationCount',
       'County'],
      dtype='str')

In [41]:
# To make it prettier and more logical, let's move the county column in between state and city 

city_level_data = city_level_data[
    ["State ID", "State", "County", "City"]
    + [col for col in city_level_data.columns if col not in ["State ID", "State", "County", "City"]]
]

In [42]:
city_level_data.head()

,State ID,State,County,City,Year,GeographicLevel,Category,Measure,Data_Value_Type,Data_Value,PopulationCount
0,CA,California,Alameda,Hayward,2017,City,Health Outcomes,Coronary heart disease among adults aged >=18 ...,Age-adjusted prevalence,4.8,"144,186"
1,CA,California,Riverside,Hemet,2017,City,Prevention,Cholesterol screening among adults aged >=18 Y...,Age-adjusted prevalence,78.0,"78,657"
2,CA,California,Riverside,Indio,2017,City,Unhealthy Behaviors,Binge drinking among adults aged >=18 Years,Age-adjusted prevalence,17.7,"76,036"
3,CA,California,Riverside,Indio,2017,City,Health Outcomes,Chronic obstructive pulmonary disease among ad...,Age-adjusted prevalence,6.0,"76,036"
4,AL,Alabama,Mobile,Mobile,2017,City,Unhealthy Behaviors,Obesity among adults aged >=18 Years,Age-adjusted prevalence,38.2,"195,111"

In [43]:
city_level_data = city_level_data.rename(columns={
    "Data_Value_Type": "Measure", 
    "Data_Value": "Prevalence",
    "PopulationCount": "Population",
    "Measure": "Health Concern",
})

In [44]:
city_level_data.head()

,State ID,State,County,City,Year,GeographicLevel,Category,Health Concern,Measure,Prevalence,Population
0,CA,California,Alameda,Hayward,2017,City,Health Outcomes,Coronary heart disease among adults aged >=18 ...,Age-adjusted prevalence,4.8,"144,186"
1,CA,California,Riverside,Hemet,2017,City,Prevention,Cholesterol screening among adults aged >=18 Y...,Age-adjusted prevalence,78.0,"78,657"
2,CA,California,Riverside,Indio,2017,City,Unhealthy Behaviors,Binge drinking among adults aged >=18 Years,Age-adjusted prevalence,17.7,"76,036"
3,CA,California,Riverside,Indio,2017,City,Health Outcomes,Chronic obstructive pulmonary disease among ad...,Age-adjusted prevalence,6.0,"76,036"
4,AL,Alabama,Mobile,Mobile,2017,City,Unhealthy Behaviors,Obesity among adults aged >=18 Years,Age-adjusted prevalence,38.2,"195,111"

In [45]:
# Now let's read in the food access data and inspect it 

food_access_data = pd.read_csv(
    "Food Access Research Atlas.csv",
    engine="python",
    quoting=3,
    on_bad_lines="skip",
    encoding_errors="ignore"
)

In [46]:
food_access_data.head()

,State,County,Urban,Population,Low Income and Low Access @ 1 and 10 Miles from Supermarket,Low Income,Poverty Rate,Median Family Income,Low Access @ 1 Mile Urban and 10 Miles Rural,Low Access at 1 Mile,...,Share Population Beyond 1 Mile,Low Income Population Beyond 1 Mile,Share of Low Income Population Beyond 1 Mile,Houses w/out Vehicle Beyond 1 Mile,Share of Houses w/out Vehicle Beyond 1 Mile,Houses Receiving SNAP Beyond 1 Mile,Share of Houses Receiving SNAP Beyond 1 Mile,Total Low Income Population,Total Houses w/out Vehicle,Total Houses Receiving SNAP
0,Alabama,Autauga County,1,1912,0,0,11.3,81250.0,1,1,...,99.19,461.0,24.11,5.0,0.79,92.0,13.22,455.0,6.0,102.0
1,Alabama,Autauga County,1,2170,1,1,17.9,49000.0,1,1,...,58.11,604.0,27.83,67.0,9.00,96.0,12.95,802.0,89.0,156.0
2,Alabama,Autauga County,1,3373,0,0,15.0,62609.0,1,1,...,46.00,478.0,14.18,0.0,0.00,74.0,5.87,1306.0,99.0,172.0
3,Alabama,Autauga County,1,4386,0,0,2.8,70607.0,1,1,...,31.09,343.0,7.83,8.0,0.46,30.0,1.76,922.0,21.0,98.0
4,Alabama,Autauga County,1,10766,0,0,15.2,96334.0,1,1,...,24.55,586.0,5.45,55.0,1.35,83.0,2.04,2242.0,230.0,339.0

In [47]:
# There are a ton of null values so let's see where the most exist, some metrics will inevitably not be tested across some rows.

food_access_data.isnull().sum()

State                                                               0
County                                                              0
Urban                                                               0
Population                                                          0
Low Income and Low Access @ 1 and 10 Miles from Supermarket         0
Low Income                                                          0
Poverty Rate                                                        3
Median Family Income                                              748
Low Access @ 1 Mile Urban and 10 Miles Rural                        0
Low Access at 1 Mile                                                0
Low Acess at 10 Miles                                               0
Population Beyond 1 Mile Urban and 10 Miles Rural               29957
Low Income Population Beyond 1 Mile Urban and 10 Miles Rural    29957
Population Count Beyond 1 Mile                                  19989
Share Population Beyond 1 Mile                                  19989
Low Income Population Beyond 1 Mile                             19989
Share of Low Income Population Beyond 1 Mile                    19989
Houses w/out Vehicle Beyond 1 Mile                              19989
Share of Houses w/out Vehicle Beyond 1 Mile                     19966
Houses Receiving SNAP Beyond 1 Mile                             19989
Share of Houses Receiving SNAP Beyond 1 Mile                    19966
Total Low Income Population                                         4
Total Houses w/out Vehicle                                          4
Total Houses Receiving SNAP                                         4
dtype: int64

In [48]:
food_access_data.isnull().sum().sort_values(ascending=False)

Low Income Population Beyond 1 Mile Urban and 10 Miles Rural    29957
Population Beyond 1 Mile Urban and 10 Miles Rural               29957
Share of Low Income Population Beyond 1 Mile                    19989
Houses w/out Vehicle Beyond 1 Mile                              19989
Share Population Beyond 1 Mile                                  19989
Population Count Beyond 1 Mile                                  19989
Houses Receiving SNAP Beyond 1 Mile                             19989
Low Income Population Beyond 1 Mile                             19989
Share of Houses Receiving SNAP Beyond 1 Mile                    19966
Share of Houses w/out Vehicle Beyond 1 Mile                     19966
Median Family Income                                              748
Total Houses w/out Vehicle                                          4
Total Houses Receiving SNAP                                         4
Total Low Income Population                                         4
Poverty Rate                                                        3
State                                                               0
Low Income and Low Access @ 1 and 10 Miles from Supermarket         0
Low Income                                                          0
Urban                                                               0
Population                                                          0
County                                                              0
Low Access at 1 Mile                                                0
Low Acess at 10 Miles                                               0
Low Access @ 1 Mile Urban and 10 Miles Rural                        0
dtype: int64

In [49]:
(
    food_access_data.isnull().mean() * 100
).sort_values(ascending=False)

Low Income Population Beyond 1 Mile Urban and 10 Miles Rural    41.302340
Population Beyond 1 Mile Urban and 10 Miles Rural               41.302340
Share of Low Income Population Beyond 1 Mile                    27.559251
Houses w/out Vehicle Beyond 1 Mile                              27.559251
Share Population Beyond 1 Mile                                  27.559251
Population Count Beyond 1 Mile                                  27.559251
Houses Receiving SNAP Beyond 1 Mile                             27.559251
Low Income Population Beyond 1 Mile                             27.559251
Share of Houses Receiving SNAP Beyond 1 Mile                    27.527540
Share of Houses w/out Vehicle Beyond 1 Mile                     27.527540
Median Family Income                                             1.031283
Total Houses w/out Vehicle                                       0.005515
Total Houses Receiving SNAP                                      0.005515
Total Low Income Population                                      0.005515
Poverty Rate                                                     0.004136
State                                                            0.000000
Low Income and Low Access @ 1 and 10 Miles from Supermarket      0.000000
Low Income                                                       0.000000
Urban                                                            0.000000
Population                                                       0.000000
County                                                           0.000000
Low Access at 1 Mile                                             0.000000
Low Acess at 10 Miles                                            0.000000
Low Access @ 1 Mile Urban and 10 Miles Rural                     0.000000
dtype: float64

In [50]:
# We can try to fill the null columns 

numeric_cols = food_access_data.select_dtypes(include="number").columns

food_access_data[numeric_cols] = (
    food_access_data[numeric_cols]
    .fillna(0)
)

In [51]:
food_access_data.head(17)

,State,County,Urban,Population,Low Income and Low Access @ 1 and 10 Miles from Supermarket,Low Income,Poverty Rate,Median Family Income,Low Access @ 1 Mile Urban and 10 Miles Rural,Low Access at 1 Mile,...,Share Population Beyond 1 Mile,Low Income Population Beyond 1 Mile,Share of Low Income Population Beyond 1 Mile,Houses w/out Vehicle Beyond 1 Mile,Share of Houses w/out Vehicle Beyond 1 Mile,Houses Receiving SNAP Beyond 1 Mile,Share of Houses Receiving SNAP Beyond 1 Mile,Total Low Income Population,Total Houses w/out Vehicle,Total Houses Receiving SNAP
0,Alabama,Autauga County,1,1912,0,0,11.3,81250.0,1,1,...,99.19,461.0,24.11,5.0,0.79,92.0,13.22,455.0,6.0,102.0
1,Alabama,Autauga County,1,2170,1,1,17.9,49000.0,1,1,...,58.11,604.0,27.83,67.0,9.00,96.0,12.95,802.0,89.0,156.0
2,Alabama,Autauga County,1,3373,0,0,15.0,62609.0,1,1,...,46.00,478.0,14.18,0.0,0.00,74.0,5.87,1306.0,99.0,172.0
3,Alabama,Autauga County,1,4386,0,0,2.8,70607.0,1,1,...,31.09,343.0,7.83,8.0,0.46,30.0,1.76,922.0,21.0,98.0
4,Alabama,Autauga County,1,10766,0,0,15.2,96334.0,1,1,...,24.55,586.0,5.45,55.0,1.35,83.0,2.04,2242.0,230.0,339.0
5,Alabama,Autauga County,1,3668,1,1,21.6,69521.0,1,1,...,93.72,1585.0,43.21,72.0,5.47,206.0,15.70,1659.0,71.0,224.0
6,Alabama,Autauga County,1,2891,1,1,30.5,39875.0,1,1,...,42.58,742.0,25.67,12.0,1.01,140.0,11.82,2175.0,34.0,390.0
7,Alabama,Autauga County,0,3081,0,0,8.9,89423.0,0,0,...,100.00,576.0,18.70,74.0,6.91,150.0,13.99,527.0,68.0,143.0
8,Alabama,Autauga County,0,10435,0,0,13.7,84833.0,0,0,...,89.51,2547.0,24.41,179.0,4.84,285.0,7.71,3103.0,198.0,352.0
9,Alabama,Autauga County,0,5675,0,0,9.8,77865.0,0,0,...,95.23,1308.0,23.05,82.0,3.97,289.0,14.00,1612.0,97.0,340.0
10,Alabama,Autauga County,0,2894,1,1,22.7,60900.0,1,0,...,100.00,1119.0,38.67,9.0,0.80,155.0,14.31,977.0,9.0,146.0
11,Alabama,Autauga County,0,3320,1,1,24.1,49833.0,1,0,...,100.00,1718.0,51.75,271.0,20.72,227.0,17.36,1463.0,269.0,230.0
12,Alabama,Baldwin County,0,3804,1,1,10.2,56464.0,1,0,...,100.00,1353.0,35.56,85.0,5.62,122.0,8.09,1496.0,84.0,126.0
13,Alabama,Baldwin County,0,2902,0,1,20.2,44954.0,0,0,...,100.00,1556.0,53.61,99.0,8.90,142.0,12.81,1715.0,91.0,146.0
14,Alabama,Baldwin County,0,7826,0,0,6.4,81799.0,0,0,...,95.37,2174.0,27.78,159.0,5.84,143.0,5.24,2492.0,181.0,165.0
15,Alabama,Baldwin County,0,4736,0,0,12.3,58359.0,0,0,...,99.47,1337.0,28.23,17.0,1.00,119.0,6.84,1347.0,19.0,120.0
16,Alabama,Baldwin County,1,4815,0,0,14.3,69951.0,1,1,...,38.91,545.0,11.31,38.0,2.11,107.0,5.93,1516.0,133.0,245.0

In [52]:
# To be able to join with the other data, we'll need to drop the word county from all of the different rows when referring to this 

food_access_data["County"] = (
    food_access_data["County"]
    .str.replace(" County", "", regex=False)
    .str.strip()
)

In [53]:
food_access_data.head()

,State,County,Urban,Population,Low Income and Low Access @ 1 and 10 Miles from Supermarket,Low Income,Poverty Rate,Median Family Income,Low Access @ 1 Mile Urban and 10 Miles Rural,Low Access at 1 Mile,...,Share Population Beyond 1 Mile,Low Income Population Beyond 1 Mile,Share of Low Income Population Beyond 1 Mile,Houses w/out Vehicle Beyond 1 Mile,Share of Houses w/out Vehicle Beyond 1 Mile,Houses Receiving SNAP Beyond 1 Mile,Share of Houses Receiving SNAP Beyond 1 Mile,Total Low Income Population,Total Houses w/out Vehicle,Total Houses Receiving SNAP
0,Alabama,Autauga,1,1912,0,0,11.3,81250.0,1,1,...,99.19,461.0,24.11,5.0,0.79,92.0,13.22,455.0,6.0,102.0
1,Alabama,Autauga,1,2170,1,1,17.9,49000.0,1,1,...,58.11,604.0,27.83,67.0,9.00,96.0,12.95,802.0,89.0,156.0
2,Alabama,Autauga,1,3373,0,0,15.0,62609.0,1,1,...,46.00,478.0,14.18,0.0,0.00,74.0,5.87,1306.0,99.0,172.0
3,Alabama,Autauga,1,4386,0,0,2.8,70607.0,1,1,...,31.09,343.0,7.83,8.0,0.46,30.0,1.76,922.0,21.0,98.0
4,Alabama,Autauga,1,10766,0,0,15.2,96334.0,1,1,...,24.55,586.0,5.45,55.0,1.35,83.0,2.04,2242.0,230.0,339.0

In [54]:
# Now we can group by and also make sure we include the exact columns in the group by, making sure they're taking the values we want as well 

food_access_county = (
    food_access_data
    .groupby(["State", "County"], as_index=False)
    .agg({
        "Urban": "mean",
        "Low Income": "mean",
        "Low Income and Low Access @ 1 and 10 Miles from Supermarket": "mean",
        "Low Access @ 1 Mile Urban and 10 Miles Rural": "mean",
        "Low Access at 1 Mile": "mean",
        "Low Acess at 10 Miles": "mean",

        **{
            col: "sum"
            for col in food_access_data.columns
            if col not in [
                "State",
                "County",
                "Urban",
                "Low Income",
                "Low Income and Low Access @ 1 and 10 Miles from Supermarket",
                "Low Access @ 1 Mile Urban and 10 Miles Rural",
                "Low Access at 1 Mile",
                "Low Acess at 10 Miles"
            ]
        }
    })
)

In [55]:
food_access_county.head()

,State,County,Urban,Low Income,Low Income and Low Access @ 1 and 10 Miles from Supermarket,Low Access @ 1 Mile Urban and 10 Miles Rural,Low Access at 1 Mile,Low Acess at 10 Miles,Population,Poverty Rate,...,Share Population Beyond 1 Mile,Low Income Population Beyond 1 Mile,Share of Low Income Population Beyond 1 Mile,Houses w/out Vehicle Beyond 1 Mile,Share of Houses w/out Vehicle Beyond 1 Mile,Houses Receiving SNAP Beyond 1 Mile,Share of Houses Receiving SNAP Beyond 1 Mile,Total Low Income Population,Total Houses w/out Vehicle,Total Houses Receiving SNAP
0,Alabama,Autauga,0.583333,0.416667,0.416667,0.750000,0.583333,0.166667,54571,193.5,...,879.98,12067.0,304.86,834.0,55.32,1827.0,130.73,17243.0,1191.0,2692.0
1,Alabama,Baldwin,0.451613,0.225806,0.129032,0.451613,0.419355,0.032258,182265,367.2,...,2312.58,38848.0,700.80,1653.0,80.79,4027.0,176.60,57843.0,2705.0,5926.0
2,Alabama,Barbour,0.222222,0.888889,0.444444,0.444444,0.111111,0.333333,27457,263.8,...,604.65,9290.0,296.00,545.0,50.43,1648.0,152.98,12073.0,849.0,2516.0
3,Alabama,Bibb,0.000000,0.250000,0.000000,0.000000,0.000000,0.000000,22915,48.7,...,336.03,6480.0,120.09,312.0,21.08,713.0,35.97,7968.0,410.0,849.0
4,Alabama,Blount,0.111111,0.333333,0.000000,0.111111,0.111111,0.000000,57322,133.7,...,798.43,18188.0,289.09,752.0,31.88,1804.0,75.32,20795.0,856.0,1966.0

In [56]:
# We can make these values more meaningful by taking into account their weighted averages

food_access_county = (
    food_access_data
    .groupby(["State", "County"])
    .apply(
        lambda x: pd.Series({
            "Population": x["Population"].sum(),

            "Poverty Rate": (
                (x["Poverty Rate"] * x["Population"]).sum()
                / x["Population"].sum()
            ),

            "Share Population Beyond 1 Mile": (
                (x["Share Population Beyond 1 Mile"] * x["Population"]).sum()
                / x["Population"].sum()
            ),

            "Share of Low Income Population Beyond 1 Mile": (
                (x["Share of Low Income Population Beyond 1 Mile"] * x["Population"]).sum()
                / x["Population"].sum()
            ),

            "Share of Houses w/out Vehicle Beyond 1 Mile": (
                (x["Share of Houses w/out Vehicle Beyond 1 Mile"] * x["Population"]).sum()
                / x["Population"].sum()
            ),

            "Share of Houses Receiving SNAP Beyond 1 Mile": (
                (x["Share of Houses Receiving SNAP Beyond 1 Mile"] * x["Population"]).sum()
                / x["Population"].sum()
            )
        })
    )
    .reset_index()
)

In [57]:
food_access_county.head()

,State,County,Population,Poverty Rate,Share Population Beyond 1 Mile,Share of Low Income Population Beyond 1 Mile,Share of Houses w/out Vehicle Beyond 1 Mile,Share of Houses Receiving SNAP Beyond 1 Mile
0,Alabama,Autauga,54571.0,15.137584,68.578638,22.116228,4.141512,9.101432
1,Alabama,Baldwin,182265.0,10.947872,72.664094,21.311019,2.315427,5.617651
2,Alabama,Barbour,27457.0,29.354518,69.220717,33.837441,6.217895,17.736116
3,Alabama,Bibb,22915.0,13.833458,76.632487,28.276944,3.851019,8.990919
4,Alabama,Blount,57322.0,14.623843,88.706977,31.730510,3.458628,8.350846

In [58]:
food_access_county.dtypes

State                                               str
County                                              str
Population                                      float64
Poverty Rate                                    float64
Share Population Beyond 1 Mile                  float64
Share of Low Income Population Beyond 1 Mile    float64
Share of Houses w/out Vehicle Beyond 1 Mile     float64
Share of Houses Receiving SNAP Beyond 1 Mile    float64
dtype: object

In [59]:
city_level_data.head()

,State ID,State,County,City,Year,GeographicLevel,Category,Health Concern,Measure,Prevalence,Population
0,CA,California,Alameda,Hayward,2017,City,Health Outcomes,Coronary heart disease among adults aged >=18 ...,Age-adjusted prevalence,4.8,"144,186"
1,CA,California,Riverside,Hemet,2017,City,Prevention,Cholesterol screening among adults aged >=18 Y...,Age-adjusted prevalence,78.0,"78,657"
2,CA,California,Riverside,Indio,2017,City,Unhealthy Behaviors,Binge drinking among adults aged >=18 Years,Age-adjusted prevalence,17.7,"76,036"
3,CA,California,Riverside,Indio,2017,City,Health Outcomes,Chronic obstructive pulmonary disease among ad...,Age-adjusted prevalence,6.0,"76,036"
4,AL,Alabama,Mobile,Mobile,2017,City,Unhealthy Behaviors,Obesity among adults aged >=18 Years,Age-adjusted prevalence,38.2,"195,111"

In [60]:
city_level_data = city_level_data.drop(
    columns=["GeographicLevel", "Year", "Measure"]
)

In [61]:
city_level_data.head()

,State ID,State,County,City,Category,Health Concern,Prevalence,Population
0,CA,California,Alameda,Hayward,Health Outcomes,Coronary heart disease among adults aged >=18 ...,4.8,"144,186"
1,CA,California,Riverside,Hemet,Prevention,Cholesterol screening among adults aged >=18 Y...,78.0,"78,657"
2,CA,California,Riverside,Indio,Unhealthy Behaviors,Binge drinking among adults aged >=18 Years,17.7,"76,036"
3,CA,California,Riverside,Indio,Health Outcomes,Chronic obstructive pulmonary disease among ad...,6.0,"76,036"
4,AL,Alabama,Mobile,Mobile,Unhealthy Behaviors,Obesity among adults aged >=18 Years,38.2,"195,111"

In [62]:
city_level_data.columns

Index(['State ID', 'State', 'County', 'City', 'Category', 'Health Concern',
       'Prevalence', 'Population'],
      dtype='str')

In [63]:
city_level_data.dtypes

State ID              str
State                 str
County                str
City                  str
Category              str
Health Concern        str
Prevalence        float64
Population            str
dtype: object

In [64]:
city_level_data["Prevalence"] = pd.to_numeric(
    city_level_data["Prevalence"],
    errors="coerce"
)

city_level_data["Population"] = pd.to_numeric(
    city_level_data["Population"],
    errors="coerce"
)

In [65]:
city_level_data.dtypes

State ID              str
State                 str
County                str
City                  str
Category              str
Health Concern        str
Prevalence        float64
Population        float64
dtype: object

In [66]:
def _norm(s: pd.Series) -> pd.Series:
    return (
        s.astype(str)
         .str.strip()
         .str.lower()
         .str.replace(r"\s+(county|parish|borough|census area|municipality)$", "", regex=True)
    )

city_level_data = city_level_data.copy()
food_access_county = food_access_county.copy()

city_level_data["_state_key"]  = _norm(city_level_data["State"])
city_level_data["_county_key"] = _norm(city_level_data["County"])
food_access_county["_state_key"]  = _norm(food_access_county["State"])
food_access_county["_county_key"] = _norm(food_access_county["County"])

In [67]:
food_cols = [
    "_state_key", "_county_key",
    "Poverty Rate",
    "Share Population Beyond 1 Mile",
    "Share of Low Income Population Beyond 1 Mile",
    "Share of Houses w/out Vehicle Beyond 1 Mile",
    "Share of Houses Receiving SNAP Beyond 1 Mile",
]

In [68]:
# We can move to merging the datasets now that we have the proper columns and everything normalized


merged = city_level_data.merge(
    food_access_county[food_cols],
    on=["_state_key", "_county_key"],
    how="left",
    validate="many_to_one",
)

merged = merged.drop(columns=["_state_key", "_county_key"])

In [69]:
unmatched = merged["Poverty Rate"].isna().sum()
total     = len(merged)
print(f"Rows: {total:,}  |  Unmatched on food access: {unmatched:,} ({unmatched/total:.1%})")
print(merged.head())

Rows: 14,000  |  Unmatched on food access: 1,092 (7.8%)
  State ID       State     County     City             Category  \
0       CA  California    Alameda  Hayward      Health Outcomes
1       CA  California  Riverside    Hemet           Prevention
2       CA  California  Riverside    Indio  Unhealthy Behaviors
3       CA  California  Riverside    Indio      Health Outcomes
4       AL     Alabama     Mobile   Mobile  Unhealthy Behaviors

                                      Health Concern  Prevalence  Population  \
0  Coronary heart disease among adults aged >=18 ...         4.8         NaN
1  Cholesterol screening among adults aged >=18 Y...        78.0         NaN
2        Binge drinking among adults aged >=18 Years        17.7         NaN
3  Chronic obstructive pulmonary disease among ad...         6.0         NaN
4               Obesity among adults aged >=18 Years        38.2         NaN

   Poverty Rate  Share Population Beyond 1 Mile  \
0     10.871873                        8.869755
1     15.083167                       31.705011
2     15.083167                       31.705011
3     15.083167                       31.705011
4     19.872054                       46.837933

   Share of Low Income Population Beyond 1 Mile  \
0                                      1.176636
1                                      9.617544
2                                      9.617544
3                                      9.617544
4                                     17.765165

   Share of Houses w/out Vehicle Beyond 1 Mile  \
0                                     0.343987
1                                     0.911942
2                                     0.911942
3                                     0.911942
4                                     2.229836

   Share of Houses Receiving SNAP Beyond 1 Mile
0                                      0.315738
1                                      2.605542
2                                      2.605542
3                                      2.605542
4                                      7.362079

In [70]:
merged.head()

,State ID,State,County,City,Category,Health Concern,Prevalence,Population,Poverty Rate,Share Population Beyond 1 Mile,Share of Low Income Population Beyond 1 Mile,Share of Houses w/out Vehicle Beyond 1 Mile,Share of Houses Receiving SNAP Beyond 1 Mile
0,CA,California,Alameda,Hayward,Health Outcomes,Coronary heart disease among adults aged >=18 ...,4.8,NaN,10.871873,8.869755,1.176636,0.343987,0.315738
1,CA,California,Riverside,Hemet,Prevention,Cholesterol screening among adults aged >=18 Y...,78.0,NaN,15.083167,31.705011,9.617544,0.911942,2.605542
2,CA,California,Riverside,Indio,Unhealthy Behaviors,Binge drinking among adults aged >=18 Years,17.7,NaN,15.083167,31.705011,9.617544,0.911942,2.605542
3,CA,California,Riverside,Indio,Health Outcomes,Chronic obstructive pulmonary disease among ad...,6.0,NaN,15.083167,31.705011,9.617544,0.911942,2.605542
4,AL,Alabama,Mobile,Mobile,Unhealthy Behaviors,Obesity among adults aged >=18 Years,38.2,NaN,19.872054,46.837933,17.765165,2.229836,7.362079

In [71]:
merged = merged.drop(columns=["Population", "City", "Category"])

In [72]:
merged.head()

,State ID,State,County,Health Concern,Prevalence,Poverty Rate,Share Population Beyond 1 Mile,Share of Low Income Population Beyond 1 Mile,Share of Houses w/out Vehicle Beyond 1 Mile,Share of Houses Receiving SNAP Beyond 1 Mile
0,CA,California,Alameda,Coronary heart disease among adults aged >=18 ...,4.8,10.871873,8.869755,1.176636,0.343987,0.315738
1,CA,California,Riverside,Cholesterol screening among adults aged >=18 Y...,78.0,15.083167,31.705011,9.617544,0.911942,2.605542
2,CA,California,Riverside,Binge drinking among adults aged >=18 Years,17.7,15.083167,31.705011,9.617544,0.911942,2.605542
3,CA,California,Riverside,Chronic obstructive pulmonary disease among ad...,6.0,15.083167,31.705011,9.617544,0.911942,2.605542
4,AL,Alabama,Mobile,Obesity among adults aged >=18 Years,38.2,19.872054,46.837933,17.765165,2.229836,7.362079

In [73]:
merged = merged.rename(columns={
    "Share Population Beyond 1 Mile": "Pct Pop > 1mi from Supermarket",
    "Share of Low Income Population Beyond 1 Mile": "Pct Low-Income > 1mi",
    "Share of Houses w/out Vehicle Beyond 1 Mile": "Pct No-Vehicle Households > 1mi",
    "Share of Houses Receiving SNAP Beyond 1 Mile": "Pct SNAP Households > 1mi",
})
merged.to_csv("merged_health_food_access.csv", index=False)

In [74]:
# Now we can turn this data into a useable CSV to obtain some locational health outcome vs income analysis

final_data = pd.read_csv(
    "merged_health_food_access.csv",
    engine="python",
    quoting=3,
    on_bad_lines="skip",
    encoding_errors="ignore"
)

In [75]:
final_data.head()

,State ID,State,County,Health Concern,Prevalence,Poverty Rate,Pct Pop > 1mi from Supermarket,Pct Low-Income > 1mi,Pct No-Vehicle Households > 1mi,Pct SNAP Households > 1mi
0,CA,California,Alameda,Coronary heart disease among adults aged >=18 ...,4.8,10.871873,8.869755,1.176636,0.343987,0.315738
1,CA,California,Riverside,Cholesterol screening among adults aged >=18 Y...,78.0,15.083167,31.705011,9.617544,0.911942,2.605542
2,CA,California,Riverside,Binge drinking among adults aged >=18 Years,17.7,15.083167,31.705011,9.617544,0.911942,2.605542
3,CA,California,Riverside,Chronic obstructive pulmonary disease among ad...,6.0,15.083167,31.705011,9.617544,0.911942,2.605542
4,AL,Alabama,Mobile,Obesity among adults aged >=18 Years,38.2,19.872054,46.837933,17.765165,2.229836,7.362079

In [76]:
import numpy as np

In [77]:
final_data["City_vs_State_z"] = (
    final_data
      .groupby(["State", "Health Concern"])["Prevalence"]
      .transform(lambda x: (x - x.mean()) / x.std())
)

In [78]:
final_data

,State ID,State,County,Health Concern,Prevalence,Poverty Rate,Pct Pop > 1mi from Supermarket,Pct Low-Income > 1mi,Pct No-Vehicle Households > 1mi,Pct SNAP Households > 1mi,City_vs_State_z
0,CA,California,Alameda,Coronary heart disease among adults aged >=18 ...,4.8,10.871873,8.869755,1.176636,0.343987,0.315738,-0.249105
1,CA,California,Riverside,Cholesterol screening among adults aged >=18 Y...,78.0,15.083167,31.705011,9.617544,0.911942,2.605542,-1.450608
2,CA,California,Riverside,Binge drinking among adults aged >=18 Years,17.7,15.083167,31.705011,9.617544,0.911942,2.605542,-0.258217
3,CA,California,Riverside,Chronic obstructive pulmonary disease among ad...,6.0,15.083167,31.705011,9.617544,0.911942,2.605542,0.885564
4,AL,Alabama,Mobile,Obesity among adults aged >=18 Years,38.2,19.872054,46.837933,17.765165,2.229836,7.362079,0.146016
...,...,...,...,...,...,...,...,...,...,...,...
12495,WI,Wisconsin,Racine,Papanicolaou smear use among adult women aged ...,76.7,12.341875,35.708275,6.122403,1.055048,2.893531,-1.497905
12496,WI,Wisconsin,Racine,Taking medicine for high blood pressure contro...,58.6,12.341875,35.708275,6.122403,1.055048,2.893531,0.352001
12497,WA,Washington,Spokane,Arthritis among adults aged >=18 Years,23.7,15.049689,31.481220,7.685890,0.836446,3.309280,0.543980
12498,WA,Washington,Spokane,High cholesterol among adults aged >=18 Years ...,28.6,15.049689,31.481220,7.685890,0.836446,3.309280,0.807127
12499,WA,Washington,Yakima,Cancer (excluding skin cancer) among adults ag...,6.2,18.319283,41.300738,16.194820,1.056282,7.108087,-0.822709

In [79]:
# We can add some columns and join with the rest of the data that will give us the mean for different columns

state_means = (
    final_data
      .groupby(["State", "Health Concern"])["Prevalence"]
      .mean()
      .rename("State_Mean_Prevalence")
      .reset_index()
)

In [80]:
state_means

,State,Health Concern,State_Mean_Prevalence
0,Alabama,All teeth lost among adults aged >=65 Years,17.016667
1,Alabama,Arthritis among adults aged >=18 Years,28.483333
2,Alabama,Binge drinking among adults aged >=18 Years,13.433333
3,Alabama,Cancer (excluding skin cancer) among adults ag...,6.216667
4,Alabama,Cholesterol screening among adults aged >=18 Y...,81.083333
...,...,...,...
1270,Wyoming,Sleeping less than 7 hours among adults aged >...,33.400000
1271,Wyoming,Stroke among adults aged >=18 Years,2.600000
1272,Wyoming,Taking medicine for high blood pressure contro...,54.000000
1273,Wyoming,Visits to dentist or dental clinic among adult...,69.200000
1274,Wyoming,Visits to doctor for routine checkup within th...,64.400000

In [81]:
state_means["State_vs_National_z"] = (
    state_means
      .groupby("Health Concern")["State_Mean_Prevalence"]
      .transform(lambda x: (x - x.mean()) / x.std())
)
state_means

,State,Health Concern,State_Mean_Prevalence,State_vs_National_z
0,Alabama,All teeth lost among adults aged >=65 Years,17.016667,0.401449
1,Alabama,Arthritis among adults aged >=18 Years,28.483333,1.897401
2,Alabama,Binge drinking among adults aged >=18 Years,13.433333,-1.633183
3,Alabama,Cancer (excluding skin cancer) among adults ag...,6.216667,0.018873
4,Alabama,Cholesterol screening among adults aged >=18 Y...,81.083333,0.852970
...,...,...,...,...
1270,Wyoming,Sleeping less than 7 hours among adults aged >...,33.400000,-0.461816
1271,Wyoming,Stroke among adults aged >=18 Years,2.600000,-1.129413
1272,Wyoming,Taking medicine for high blood pressure contro...,54.000000,-0.905734
1273,Wyoming,Visits to dentist or dental clinic among adult...,69.200000,1.000645
1274,Wyoming,Visits to doctor for routine checkup within th...,64.400000,-0.815325

In [82]:
final_data = final_data.merge(state_means, on=["State", "Health Concern"], how="left")

In [83]:
final_data

,State ID,State,County,Health Concern,Prevalence,Poverty Rate,Pct Pop > 1mi from Supermarket,Pct Low-Income > 1mi,Pct No-Vehicle Households > 1mi,Pct SNAP Households > 1mi,City_vs_State_z,State_Mean_Prevalence,State_vs_National_z
0,CA,California,Alameda,Coronary heart disease among adults aged >=18 ...,4.8,10.871873,8.869755,1.176636,0.343987,0.315738,-0.249105,4.998347,-1.113184
1,CA,California,Riverside,Cholesterol screening among adults aged >=18 Y...,78.0,15.083167,31.705011,9.617544,0.911942,2.605542,-1.450608,80.387603,0.607412
2,CA,California,Riverside,Binge drinking among adults aged >=18 Years,17.7,15.083167,31.705011,9.617544,0.911942,2.605542,-0.258217,18.202479,0.160252
3,CA,California,Riverside,Chronic obstructive pulmonary disease among ad...,6.0,15.083167,31.705011,9.617544,0.911942,2.605542,0.885564,5.071901,-1.108758
4,AL,Alabama,Mobile,Obesity among adults aged >=18 Years,38.2,19.872054,46.837933,17.765165,2.229836,7.362079,0.146016,37.483333,1.307036
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12495,WI,Wisconsin,Racine,Papanicolaou smear use among adult women aged ...,76.7,12.341875,35.708275,6.122403,1.055048,2.893531,-1.497905,79.828571,0.626333
12496,WI,Wisconsin,Racine,Taking medicine for high blood pressure contro...,58.6,12.341875,35.708275,6.122403,1.055048,2.893531,0.352001,57.742857,-0.105951
12497,WA,Washington,Spokane,Arthritis among adults aged >=18 Years,23.7,15.049689,31.481220,7.685890,0.836446,3.309280,0.543980,22.535714,-0.283019
12498,WA,Washington,Spokane,High cholesterol among adults aged >=18 Years ...,28.6,15.049689,31.481220,7.685890,0.836446,3.309280,0.807127,27.664286,-0.834926
12499,WA,Washington,Yakima,Cancer (excluding skin cancer) among adults ag...,6.2,18.319283,41.300738,16.194820,1.056282,7.108087,-0.822709,6.357143,0.453902

In [84]:
# Let's bring in the Feeding America data 

more_food = pd.read_csv(
    "MMG2019_2017Data_ToShare.csv",
    engine="python",
    quoting=3,
    on_bad_lines="skip",
    encoding_errors="ignore"
)

In [85]:
more_food

,,,,FIPS,State,"""County","State""",2017 Food Insecurity Rate,# of Food Insecure Persons in 2017,Low Threshold in state,Low Threshold Type,High Threshold in state,High Threshold Type,% FI ≤ Low Threshold,% FI Btwn Thresholds,% FI > High Threshold,2017 Child food insecurity rate,# of Food Insecure Children in 2017,% food insecure children in HH w/ HH incomes below 185 FPL in 2017,% food insecure children in HH w/ HH incomes above 185 FPL in 2017,2017 Cost Per Meal,2017 Weighted Annual Food Budget Shortfall
1001,AL,"""Autauga County","Alabama""",13.2%,""" 7","270 """,130%,SNAP,185%,Other Nutrition Program,48.5%,14.4%,37.1%,19.8%,""" 2","670 """,66%,34%,$3.19,"""$3",957,"000.00"""
1003,AL,"""Baldwin County","Alabama""",11.6%,""" 23","560 """,130%,SNAP,185%,Other Nutrition Program,45.5%,14.4%,40.1%,18.9%,""" 8","480 """,66%,34%,$3.57,"""$14",361,"000.00"""
1005,AL,"""Barbour County","Alabama""",22.0%,""" 5","760 """,130%,SNAP,185%,Other Nutrition Program,60.1%,17.1%,22.9%,27.6%,""" 1","520 """,79%,21%,$3.09,"""$3",035,"000.00"""
1007,AL,"""Bibb County","Alabama""",14.3%,""" 3","240 """,130%,SNAP,185%,Other Nutrition Program,45.9%,18.5%,35.6%,22.1%,""" 1","050 """,84%,16%,$3.05,"""$1",684,"000.00"""
1009,AL,"""Blount County","Alabama""",10.7%,""" 6","140 """,130%,SNAP,185%,Other Nutrition Program,54.2%,20.6%,25.3%,21.2%,""" 2","880 """,76%,24%,$3.10,"""$3",249,"000.00"""
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56037,WY,"""Sweetwater County","Wyoming""",10.7%,""" 4","750 """,130%,SNAP,185%,Other Nutrition Program,43.0%,12.8%,44.2%,17.0%,""" 2","030 """,51%,49%,$3.14,"""$2",542,"000.00"""
56039,WY,"""Teton County","Wyoming""",9.7%,""" 2","220 """,130%,SNAP,185%,Other Nutrition Program,36.0%,16.7%,47.3%,11.7%,520,56%,44%,$4.20,"""$1",592,"000.00""",NaN
56041,WY,"""Uinta County","Wyoming""",12.8%,""" 2","660 """,130%,SNAP,185%,Other Nutrition Program,56.2%,7.4%,36.5%,18.9%,""" 1","160 """,64%,36%,$2.95,"""$1",340,"000.00"""
56043,WY,"""Washakie County","Wyoming""",11.2%,920,130%,SNAP,185%,Other Nutrition Program,50.5%,17.2%,32.3%,17.4%,350,74%,27%,$3.16,"""$497","000.00""",NaN,NaN,NaN
56045,WY,"""Weston County","Wyoming""",13.1%,940,130%,SNAP,185%,Other Nutrition Program,41.7%,11.9%,46.4%,20.2%,300,61%,40%,$3.15,"""$505","000.00""",NaN,NaN,NaN

In [86]:
# Fixing this import as well by shifting header

more_food = pd.read_csv(
    "MMG2019_2017Data_ToShare.csv",
    sep=",",
    header=0
)

In [87]:
print(more_food.columns)
more_food.head()

Index(['FIPS', 'State', 'County, State', '2017 Food Insecurity Rate',
       '# of Food Insecure Persons in 2017', 'Low Threshold in state',
       'Low Threshold Type', 'High Threshold in state', 'High Threshold Type',
       '% FI ≤ Low Threshold', '% FI Btwn Thresholds', '% FI > High Threshold',
       '2017 Child food insecurity rate',
       '# of Food Insecure Children in 2017',
       '% food insecure children in HH w/ HH incomes below 185 FPL in 2017',
       '% food insecure children in HH w/ HH incomes above 185 FPL in 2017',
       '2017 Cost Per Meal', '2017 Weighted Annual Food Budget Shortfall'],
      dtype='str')

,FIPS,State,"County, State",2017 Food Insecurity Rate,# of Food Insecure Persons in 2017,Low Threshold in state,Low Threshold Type,High Threshold in state,High Threshold Type,% FI ≤ Low Threshold,% FI Btwn Thresholds,% FI > High Threshold,2017 Child food insecurity rate,# of Food Insecure Children in 2017,% food insecure children in HH w/ HH incomes below 185 FPL in 2017,% food insecure children in HH w/ HH incomes above 185 FPL in 2017,2017 Cost Per Meal,2017 Weighted Annual Food Budget Shortfall
0,1001,AL,"Autauga County, Alabama",13.2%,"7,270",130%,SNAP,185%,Other Nutrition Program,48.5%,14.4%,37.1%,19.8%,"2,670",66%,34%,$3.19,"$3,957,000.00"
1,1003,AL,"Baldwin County, Alabama",11.6%,"23,560",130%,SNAP,185%,Other Nutrition Program,45.5%,14.4%,40.1%,18.9%,"8,480",66%,34%,$3.57,"$14,361,000.00"
2,1005,AL,"Barbour County, Alabama",22.0%,"5,760",130%,SNAP,185%,Other Nutrition Program,60.1%,17.1%,22.9%,27.6%,"1,520",79%,21%,$3.09,"$3,035,000.00"
3,1007,AL,"Bibb County, Alabama",14.3%,"3,240",130%,SNAP,185%,Other Nutrition Program,45.9%,18.5%,35.6%,22.1%,"1,050",84%,16%,$3.05,"$1,684,000.00"
4,1009,AL,"Blount County, Alabama",10.7%,"6,140",130%,SNAP,185%,Other Nutrition Program,54.2%,20.6%,25.3%,21.2%,"2,880",76%,24%,$3.10,"$3,249,000.00"

In [88]:
# Lots of columns to drop, let's just keep the ones we want

more_food = more_food[[
    'State',
    'County, State',
    '2017 Food Insecurity Rate',
    '# of Food Insecure Persons in 2017',
    '2017 Weighted Annual Food Budget Shortfall'
]]

In [89]:
more_food.head()

,State,"County, State",2017 Food Insecurity Rate,# of Food Insecure Persons in 2017,2017 Weighted Annual Food Budget Shortfall
0,AL,"Autauga County, Alabama",13.2%,"7,270","$3,957,000.00"
1,AL,"Baldwin County, Alabama",11.6%,"23,560","$14,361,000.00"
2,AL,"Barbour County, Alabama",22.0%,"5,760","$3,035,000.00"
3,AL,"Bibb County, Alabama",14.3%,"3,240","$1,684,000.00"
4,AL,"Blount County, Alabama",10.7%,"6,140","$3,249,000.00"

In [90]:
# Same problem with the County, but state appears as well, let's strip and only keep the first part before county, state

more_food['County'] = (
    more_food['County, State']
    .str.split(',')
    .str[0]
    .str.replace(' County', '', regex=False)
    .str.strip()
)

In [91]:
more_food

,State,"County, State",2017 Food Insecurity Rate,# of Food Insecure Persons in 2017,2017 Weighted Annual Food Budget Shortfall,County
0,AL,"Autauga County, Alabama",13.2%,"7,270","$3,957,000.00",Autauga
1,AL,"Baldwin County, Alabama",11.6%,"23,560","$14,361,000.00",Baldwin
2,AL,"Barbour County, Alabama",22.0%,"5,760","$3,035,000.00",Barbour
3,AL,"Bibb County, Alabama",14.3%,"3,240","$1,684,000.00",Bibb
4,AL,"Blount County, Alabama",10.7%,"6,140","$3,249,000.00",Blount
...,...,...,...,...,...,...
3137,WY,"Sweetwater County, Wyoming",10.7%,"4,750","$2,542,000.00",Sweetwater
3138,WY,"Teton County, Wyoming",9.7%,"2,220","$1,592,000.00",Teton
3139,WY,"Uinta County, Wyoming",12.8%,"2,660","$1,340,000.00",Uinta
3140,WY,"Washakie County, Wyoming",11.2%,920,"$497,000.00",Washakie
3141,WY,"Weston County, Wyoming",13.1%,940,"$505,000.00",Weston

In [92]:
# Seems it just made a separate county column so let's just drop the County, state column 

more_food = more_food.drop(columns=['County, State'])

In [93]:
more_food

,State,2017 Food Insecurity Rate,# of Food Insecure Persons in 2017,2017 Weighted Annual Food Budget Shortfall,County
0,AL,13.2%,"7,270","$3,957,000.00",Autauga
1,AL,11.6%,"23,560","$14,361,000.00",Baldwin
2,AL,22.0%,"5,760","$3,035,000.00",Barbour
3,AL,14.3%,"3,240","$1,684,000.00",Bibb
4,AL,10.7%,"6,140","$3,249,000.00",Blount
...,...,...,...,...,...
3137,WY,10.7%,"4,750","$2,542,000.00",Sweetwater
3138,WY,9.7%,"2,220","$1,592,000.00",Teton
3139,WY,12.8%,"2,660","$1,340,000.00",Uinta
3140,WY,11.2%,920,"$497,000.00",Washakie
3141,WY,13.1%,940,"$505,000.00",Weston

In [94]:
# Let's move the columns to look better

cols = list(more_food.columns)
cols.remove('County')
state_index = cols.index('State')
cols.insert(state_index + 1, 'County')
more_food = more_food[cols]

In [95]:
more_food

,State,County,2017 Food Insecurity Rate,# of Food Insecure Persons in 2017,2017 Weighted Annual Food Budget Shortfall
0,AL,Autauga,13.2%,"7,270","$3,957,000.00"
1,AL,Baldwin,11.6%,"23,560","$14,361,000.00"
2,AL,Barbour,22.0%,"5,760","$3,035,000.00"
3,AL,Bibb,14.3%,"3,240","$1,684,000.00"
4,AL,Blount,10.7%,"6,140","$3,249,000.00"
...,...,...,...,...,...
3137,WY,Sweetwater,10.7%,"4,750","$2,542,000.00"
3138,WY,Teton,9.7%,"2,220","$1,592,000.00"
3139,WY,Uinta,12.8%,"2,660","$1,340,000.00"
3140,WY,Washakie,11.2%,920,"$497,000.00"
3141,WY,Weston,13.1%,940,"$505,000.00"

In [96]:
# Let's group this with the earlier data 

merged = merged.merge(
    more_food,
    left_on=['State ID', 'County'],
    right_on=['State', 'County'],
    how='left'
)

In [97]:
merged.head()

,State ID,State_x,County,Health Concern,Prevalence,Poverty Rate,Pct Pop > 1mi from Supermarket,Pct Low-Income > 1mi,Pct No-Vehicle Households > 1mi,Pct SNAP Households > 1mi,State_y,2017 Food Insecurity Rate,# of Food Insecure Persons in 2017,2017 Weighted Annual Food Budget Shortfall
0,CA,California,Alameda,Coronary heart disease among adults aged >=18 ...,4.8,10.871873,8.869755,1.176636,0.343987,0.315738,CA,12.2%,"198,950","$128,941,000.00"
1,CA,California,Riverside,Cholesterol screening among adults aged >=18 Y...,78.0,15.083167,31.705011,9.617544,0.911942,2.605542,CA,9.4%,"221,660","$116,261,000.00"
2,CA,California,Riverside,Binge drinking among adults aged >=18 Years,17.7,15.083167,31.705011,9.617544,0.911942,2.605542,CA,9.4%,"221,660","$116,261,000.00"
3,CA,California,Riverside,Chronic obstructive pulmonary disease among ad...,6.0,15.083167,31.705011,9.617544,0.911942,2.605542,CA,9.4%,"221,660","$116,261,000.00"
4,AL,Alabama,Mobile,Obesity among adults aged >=18 Years,38.2,19.872054,46.837933,17.765165,2.229836,7.362079,AL,17.9%,"74,120","$40,045,000.00"

In [98]:
merged

,State ID,State_x,County,Health Concern,Prevalence,Poverty Rate,Pct Pop > 1mi from Supermarket,Pct Low-Income > 1mi,Pct No-Vehicle Households > 1mi,Pct SNAP Households > 1mi,State_y,2017 Food Insecurity Rate,# of Food Insecure Persons in 2017,2017 Weighted Annual Food Budget Shortfall
0,CA,California,Alameda,Coronary heart disease among adults aged >=18 ...,4.8,10.871873,8.869755,1.176636,0.343987,0.315738,CA,12.2%,"198,950","$128,941,000.00"
1,CA,California,Riverside,Cholesterol screening among adults aged >=18 Y...,78.0,15.083167,31.705011,9.617544,0.911942,2.605542,CA,9.4%,"221,660","$116,261,000.00"
2,CA,California,Riverside,Binge drinking among adults aged >=18 Years,17.7,15.083167,31.705011,9.617544,0.911942,2.605542,CA,9.4%,"221,660","$116,261,000.00"
3,CA,California,Riverside,Chronic obstructive pulmonary disease among ad...,6.0,15.083167,31.705011,9.617544,0.911942,2.605542,CA,9.4%,"221,660","$116,261,000.00"
4,AL,Alabama,Mobile,Obesity among adults aged >=18 Years,38.2,19.872054,46.837933,17.765165,2.229836,7.362079,AL,17.9%,"74,120","$40,045,000.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13995,WI,Wisconsin,Racine,Taking medicine for high blood pressure contro...,58.6,12.341875,35.708275,6.122403,1.055048,2.893531,WI,10.0%,"19,500","$9,416,000.00"
13996,WA,Washington,Spokane,Arthritis among adults aged >=18 Years,23.7,15.049689,31.481220,7.685890,0.836446,3.309280,WA,14.1%,"69,230","$35,421,000.00"
13997,WA,Washington,Spokane,High cholesterol among adults aged >=18 Years ...,28.6,15.049689,31.481220,7.685890,0.836446,3.309280,WA,14.1%,"69,230","$35,421,000.00"
13998,WA,Washington,Yakima,Cancer (excluding skin cancer) among adults ag...,6.2,18.319283,41.300738,16.194820,1.056282,7.108087,WA,9.4%,"23,330","$11,725,000.00"
13999,WI,Wisconsin,Milwaukee,Older adult women aged >=65 Years who are up t...,26.9,20.587983,8.604545,2.315406,0.681579,1.111752,WI,15.4%,"147,430","$70,920,000.00"

In [99]:
# Some columns to drop and rename 

merged = merged.drop(columns=[
    'State_y',
])

merged = merged.rename(columns={
    'State_x' : 'State'
})

In [100]:
merged.head()

,State ID,State,County,Health Concern,Prevalence,Poverty Rate,Pct Pop > 1mi from Supermarket,Pct Low-Income > 1mi,Pct No-Vehicle Households > 1mi,Pct SNAP Households > 1mi,2017 Food Insecurity Rate,# of Food Insecure Persons in 2017,2017 Weighted Annual Food Budget Shortfall
0,CA,California,Alameda,Coronary heart disease among adults aged >=18 ...,4.8,10.871873,8.869755,1.176636,0.343987,0.315738,12.2%,"198,950","$128,941,000.00"
1,CA,California,Riverside,Cholesterol screening among adults aged >=18 Y...,78.0,15.083167,31.705011,9.617544,0.911942,2.605542,9.4%,"221,660","$116,261,000.00"
2,CA,California,Riverside,Binge drinking among adults aged >=18 Years,17.7,15.083167,31.705011,9.617544,0.911942,2.605542,9.4%,"221,660","$116,261,000.00"
3,CA,California,Riverside,Chronic obstructive pulmonary disease among ad...,6.0,15.083167,31.705011,9.617544,0.911942,2.605542,9.4%,"221,660","$116,261,000.00"
4,AL,Alabama,Mobile,Obesity among adults aged >=18 Years,38.2,19.872054,46.837933,17.765165,2.229836,7.362079,17.9%,"74,120","$40,045,000.00"

In [101]:
# Let's drop the other parts about locational data for a cleaner look at the different things we would want from this data set 

merged = merged.drop(columns=[
    'Pct Pop > 1mi from Supermarket',
    'Pct Low-Income > 1mi',
    'Pct No-Vehicle Households > 1mi',
    'Pct SNAP Households > 1mi'
])

In [102]:
merged.head()

,State ID,State,County,Health Concern,Prevalence,Poverty Rate,2017 Food Insecurity Rate,# of Food Insecure Persons in 2017,2017 Weighted Annual Food Budget Shortfall
0,CA,California,Alameda,Coronary heart disease among adults aged >=18 ...,4.8,10.871873,12.2%,"198,950","$128,941,000.00"
1,CA,California,Riverside,Cholesterol screening among adults aged >=18 Y...,78.0,15.083167,9.4%,"221,660","$116,261,000.00"
2,CA,California,Riverside,Binge drinking among adults aged >=18 Years,17.7,15.083167,9.4%,"221,660","$116,261,000.00"
3,CA,California,Riverside,Chronic obstructive pulmonary disease among ad...,6.0,15.083167,9.4%,"221,660","$116,261,000.00"
4,AL,Alabama,Mobile,Obesity among adults aged >=18 Years,38.2,19.872054,17.9%,"74,120","$40,045,000.00"

In [103]:
# Let's just take a quick look at the different health concerns and how much they pop up that pop up so we can limit the ones that come up in the data 

health_prevalence = (
    merged.groupby('Health Concern')['Prevalence']
    .mean()
    .sort_values(ascending=False)
)

print(health_prevalence)

Health Concern
Cholesterol screening among adults aged >=18 Years                                                                                                                                                79.436200
Papanicolaou smear use among adult women aged 21–65 Years                                                                                                                                         78.357395
Mammography use among women aged 50–74 Years                                                                                                                                                      74.433000
Visits to doctor for routine checkup within the past Year among adults aged >=18 Years                                                                                                            68.589800
Fecal occult blood test, sigmoidoscopy, or colonoscopy among adults aged 50–75 Years                                                                                                              64.135000
Visits to dentist or dental clinic among adults aged >=18 Years                                                                                                                                   63.276200
Taking medicine for high blood pressure control among adults aged >=18 Years with high blood pressure                                                                                             56.504000
Sleeping less than 7 hours among adults aged >=18 Years                                                                                                                                           35.521200
Older adult men aged >=65 Years who are up to date on a core set of clinical preventive services: Flu shot past Year, PPV shot ever, Colorectal cancer screening                                  34.041600
Older adult women aged >=65 Years who are up to date on a core set of clinical preventive services: Flu shot past Year, PPV shot ever, Colorectal cancer screening, and Mammogram past 2 Years    31.926000
High blood pressure among adults aged >=18 Years                                                                                                                                                  30.583200
Obesity among adults aged >=18 Years                                                                                                                                                              30.241600
High cholesterol among adults aged >=18 Years who have been screened in the past 5 Years                                                                                                          29.309800
No leisure-time physical activity among adults aged >=18 Years                                                                                                                                    26.525000
Arthritis among adults aged >=18 Years                                                                                                                                                            22.102400
Binge drinking among adults aged >=18 Years                                                                                                                                                       17.685400
Current smoking among adults aged >=18 Years                                                                                                                                                      17.264200
Current lack of health insurance among adults aged 18–64 Years                                                                                                                                    16.308800
All teeth lost among adults aged >=65 Years                                                                                                                                                       14.593000
Mental health not good for >=14 days among adults aged >=18 Years                                                                                                                                 13.416800
Physical health not good for >=14 days among adults aged >=18 Years                                                                                                                               12.630200
Diagnosed diabetes among adults aged >=18 Years                                                                                                                                                   10.458200
Current asthma among adults aged >=18 Years                                                                                                                                                        9.464800
Chronic obstructive pulmonary disease among adults aged >=18 Years                                                                                                                                 6.256800
Cancer (excluding skin cancer) among adults aged >=18 Years                                                                                                                                        6.058600
Coronary heart disease among adults aged >=18 Years                                                                                                                                                5.676000
Stroke among adults aged >=18 Years                                                                                                                                                                3.122000
Chronic kidney disease among adults aged >=18 Years                                                                                                                                                3.069000
Name: Prevalence, dtype: float64

In [104]:
health_prevalence

Health Concern
Cholesterol screening among adults aged >=18 Years                                                                                                                                                79.436200
Papanicolaou smear use among adult women aged 21–65 Years                                                                                                                                         78.357395
Mammography use among women aged 50–74 Years                                                                                                                                                      74.433000
Visits to doctor for routine checkup within the past Year among adults aged >=18 Years                                                                                                            68.589800
Fecal occult blood test, sigmoidoscopy, or colonoscopy among adults aged 50–75 Years                                                                                                              64.135000
Visits to dentist or dental clinic among adults aged >=18 Years                                                                                                                                   63.276200
Taking medicine for high blood pressure control among adults aged >=18 Years with high blood pressure                                                                                             56.504000
Sleeping less than 7 hours among adults aged >=18 Years                                                                                                                                           35.521200
Older adult men aged >=65 Years who are up to date on a core set of clinical preventive services: Flu shot past Year, PPV shot ever, Colorectal cancer screening                                  34.041600
Older adult women aged >=65 Years who are up to date on a core set of clinical preventive services: Flu shot past Year, PPV shot ever, Colorectal cancer screening, and Mammogram past 2 Years    31.926000
High blood pressure among adults aged >=18 Years                                                                                                                                                  30.583200
Obesity among adults aged >=18 Years                                                                                                                                                              30.241600
High cholesterol among adults aged >=18 Years who have been screened in the past 5 Years                                                                                                          29.309800
No leisure-time physical activity among adults aged >=18 Years                                                                                                                                    26.525000
Arthritis among adults aged >=18 Years                                                                                                                                                            22.102400
Binge drinking among adults aged >=18 Years                                                                                                                                                       17.685400
Current smoking among adults aged >=18 Years                                                                                                                                                      17.264200
Current lack of health insurance among adults aged 18–64 Years                                                                                                                                    16.308800
All teeth lost among adults aged >=65 Years                                                                                                                                                       14.593000
Mental health not good for >=14 days among adults aged >=18 Years                                                                                                                                 13.416800
Physical health not good for >=14 days among adults aged >=18 Years                                                                                                                               12.630200
Diagnosed diabetes among adults aged >=18 Years                                                                                                                                                   10.458200
Current asthma among adults aged >=18 Years                                                                                                                                                        9.464800
Chronic obstructive pulmonary disease among adults aged >=18 Years                                                                                                                                 6.256800
Cancer (excluding skin cancer) among adults aged >=18 Years                                                                                                                                        6.058600
Coronary heart disease among adults aged >=18 Years                                                                                                                                                5.676000
Stroke among adults aged >=18 Years                                                                                                                                                                3.122000
Chronic kidney disease among adults aged >=18 Years                                                                                                                                                3.069000
Name: Prevalence, dtype: float64

In [105]:
# Let's just keep 5 that are relevant and show up enough in the data to be a good representation

selected_concerns = [ 
    'Obesity among adults aged >=18 Years', 
    'High cholesterol among adults aged >=18 Years who have been screened in the past 5 Years',
    'High blood pressure among adults aged >=18 Years ',
    'Sleeping less than 7 hours among adults aged >=18 Years', 
    'Visits to doctor for routine checkup within the past Year among adults aged >=18 Years'
]

In [106]:
merged = merged[
    merged['Health Concern'].isin(selected_concerns)
]

In [107]:
merged.head()

,State ID,State,County,Health Concern,Prevalence,Poverty Rate,2017 Food Insecurity Rate,# of Food Insecure Persons in 2017,2017 Weighted Annual Food Budget Shortfall
4,AL,Alabama,Mobile,Obesity among adults aged >=18 Years,38.2,19.872054,17.9%,"74,120","$40,045,000.00"
12,CA,California,Riverside,Obesity among adults aged >=18 Years,26.8,15.083167,9.4%,"221,660","$116,261,000.00"
15,CA,California,Orange,Obesity among adults aged >=18 Years,20.5,11.614614,9.2%,"290,660","$170,726,000.00"
24,CA,California,San Diego,Obesity among adults aged >=18 Years,22.4,12.540432,11.0%,"360,530","$207,910,000.00"
31,FL,Florida,Pinellas,Obesity among adults aged >=18 Years,29.4,13.088289,14.2%,"134,650","$78,298,000.00"

In [108]:
# Now we have another csv to work with in Tableau

merged.to_csv("tableau_food_health.csv", index=False)

print("CSV saved as tableau_food_health.csv")

CSV saved as tableau_food_health.csv